name: CI

on:
  push:
    branches:
      - test/*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Merge upstream changes
      run: |
        git remote add upstream https://github.com/tilsong2/TestGithubAction2.git
        git fetch upstream
        git merge upstream/main

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "adopt"

    - name: make application.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES_DEV }}" > ./application.properties
      shell: bash

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build
